# Generated by Django 5.2.13 on 2026-04-12 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('motoristas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('placa', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Placa')),
                ('tipo_vinculo', models.CharField(choices=[('proprio', 'Próprio'), ('terceiro', 'Terceiro'), ('agregado', 'Agregado')], max_length=20, verbose_name='Tipo de Vínculo')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('tipo_carroceria', models.CharField(choices=[('bau', 'Baú'), ('graneleiro', 'Graneleiro'), ('frigorifico', 'Frigorífico'), ('plataforma', 'Plataforma'), ('grade_baixa', 'Grade Baixa'), ('sider', 'Sider'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Carroceria')),
                ('capacidade_carga', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidade de Carga (kg)')),
                ('qtd_palete', models.PositiveSmallIntegerField(verbose_name='Qtd. de Paletes')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('manutencao', 'Em Manutenção')], default='ativo', max_length=15, verbose_name='Status')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='empresas.empresa', verbose_name='Empresa')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos', to='motoristas.motorista', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['placa'],
            },
        ),
    ]
