# Generated by Django 5.2.13 on 2026-04-12 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaDescarga',
            fields=[
                ('cnpj_cpf', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='CNPJ / CPF')),
                ('nome', models.CharField(max_length=200, verbose_name='Razão Social / Nome')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='Nome Fantasia')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas_descarga', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Empresa de Descarga',
                'verbose_name_plural': 'Empresas de Descarga',
                'ordering': ['nome'],
            },
        ),
    ]
