# Generated by Django 5.2.13 on 2026-04-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_descarga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresadescarga',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empresadescarga',
            name='cnpj_cpf',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ / CPF'),
        ),
    ]
