# Generated by Django 5.2.13 on 2026-04-12 14:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
        ('empresas_descarga', '0001_initial'),
        ('motoristas', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_transporte', models.CharField(editable=False, max_length=10, unique=True, verbose_name='Nº Transporte')),
                ('documento_transporte', models.CharField(blank=True, max_length=50, verbose_name='Documento')),
                ('data_transporte', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data do Transporte')),
                ('status_transporte', models.CharField(choices=[('programado', 'Programado'), ('em_andamento', 'Em Andamento'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='programado', max_length=20, verbose_name='Status')),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status Pagamento')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto (R$)')),
                ('acrescimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Acréscimo (R$)')),
                ('adiantamento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Adiantamento (R$)')),
                ('frete_terceiro', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frete Terceiro (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportes', to='empresas.empresa', verbose_name='Empresa')),
                ('empresa_descarga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportes', to='empresas_descarga.empresadescarga', verbose_name='Empresa de Descarga')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportes', to='motoristas.motorista', verbose_name='Motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportes', to='veiculos.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
                'ordering': ['-data_transporte', '-numero_transporte'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallets', models.PositiveSmallIntegerField(default=0, verbose_name='Qtd. Pallets')),
                ('valor_pallet', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por Palete (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total (R$)')),
                ('ordem_entrega', models.PositiveSmallIntegerField(default=1, verbose_name='Ordem')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='clientes.cliente', verbose_name='Cliente')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='transportes.transporte', verbose_name='Transporte')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['ordem_entrega'],
            },
        ),
    ]
