# Generated by Django 5.2.13 on 2026-04-12 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_descarga', '0002_empresadescarga_id_alter_empresadescarga_cnpj_cpf'),
        ('transportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporte',
            name='empresa_descarga',
        ),
        migrations.AddField(
            model_name='entrega',
            name='empresa_descarga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='empresas_descarga.empresadescarga', verbose_name='Empresa de Descarga'),
        ),
    ]
