# Generated by Django 5.2.13 on 2026-04-12 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo_cliente', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código do Cliente')),
                ('nome_femsa', models.CharField(max_length=200, verbose_name='Nome Femsa / Razão Social')),
                ('nome_mercado', models.CharField(max_length=200, verbose_name='Nome Mercado / Fantasia')),
                ('tipo_equipamento', models.CharField(choices=[('vuc', 'VUC'), ('toco', 'Toco'), ('truck', 'Truck'), ('carreta', 'Carreta'), ('bitruck', 'Bitruck'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Equipamento')),
                ('tipo_descarga', models.CharField(choices=[('manual', 'Manual'), ('mecanica', 'Mecânica'), ('ambos', 'Manual e Mecânica')], max_length=20, verbose_name='Tipo de Descarga')),
                ('qtd_chapas', models.PositiveSmallIntegerField(default=0, verbose_name='Qtd. Chapas')),
                ('valor_tipo', models.CharField(choices=[('por_palete', 'Por Palete'), ('carga_cheia', 'Carga Cheia'), ('descarga_direto', 'Descarga Direto')], max_length=20, verbose_name='Tipo de Cobrança')),
                ('valor_pallet', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por Palete / Frete')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome_femsa'],
            },
        ),
    ]
