# Generated by Django 5.2.13 on 2026-04-12 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='CPF')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('cnh', models.CharField(max_length=20, unique=True, verbose_name='Nº CNH')),
                ('categoria_cnh', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('AB', 'AB'), ('AC', 'AC'), ('AD', 'AD'), ('AE', 'AE')], max_length=5, verbose_name='Categoria CNH')),
                ('data_vencimento_cnh', models.DateField(verbose_name='Vencimento CNH')),
                ('data_expedicao_cnh', models.DateField(verbose_name='Expedição CNH')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10, verbose_name='Status')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motoristas', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['nome'],
            },
        ),
    ]
